language: node_js

node_js:
   - node # will use latest node

before_script: # commands to run before the build step
  - npm install -g --silent @angular/cli
  - npm install -g --silent firebase-tools

script: # the build step
   - ng build --prod
   

deploy:
  provider: firebase
  token:
    secure: "1/ypj1aP7c406N7Xu3b-ZP2uo6ZsFEgSq7510NhDN9Aqo"
  project: "gastos-claros"